---
- name: OS misc packages
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    # Ubuntu-16, Debian-9, CentOS-6
    - "{{ ansible_distribution }}.yml"
    # Ubuntu, Debian, CentOS
    - "{{ ansible_os_family }}.yml"
    # Debian, RedHat
    - "default.yml"

- package:
    name: "{{ os_misc_pkgs }}"
    state: latest
    update_cache: true

- name: NTP service  
  service: name="{{ ntp_service }}" enabled=yes state=started
