---
# SSLH: connection multiplexer
- name: sslh protocol multiplexer
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    # Ubuntu-16, Debian-9, CentOS-6
    - "{{ ansible_distribution }}.yml"
    # Ubuntu, Debian, CentOS
    - "{{ ansible_os_family }}.yml"
    # Debian, RedHat
    - "default.yml"

- action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=latest
  with_items: "{{ sslh_pkgs }}"

- name: sslh configuration files
  template:
    src:   "{{ item.src }}"
    dest:  "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode:  "{{ item.mode }}"
  notify:  "{{ item.notify | default(omit) }}"
  with_items: "{{ sslh_templates }}"

- name: sslh service  
  service: name="{{ sslh_service }}" enabled=yes state=started
