---
- name: restart openvpn
  service: name="{{ openvpn_service }}" state=restarted

- name: restart openvpn daemon-reload
  service: name="{{ openvpn_service }}" state=restarted daemon_reload=yes
  when: ansible_service_mgr = 'systemd'