---
#
# Main block for personalWGserver
#
# PENDING. On ubuntu 16, there's no Python2, so:
#  https://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found

- name: personalWGserver configuration
  hosts: all
  become: yes
  vars_files:
    - WGserver_vars.yml
  roles:
    - 'os_misc'
    - 'security'
    - 'firewall'
    - 'vpn'
    # - apache2
    - sslh
    - fail2ban
    # - owncloud
    # - exim4
    # - horde
    # - spamassasin

